### ISSUE TITLE
Doesn't work on Rpi4 running Ubuntu Server arm64

### ISSUE THREAD

**Issue by antonyshen** [kz6fittycent/pihole-snap#1]
Hi,

Just tried this snap, I can see similar complaint in several sub-commands like below: 
ubuntu@usfrpi4:~$ pihole-snap status
/snap/pihole-snap/21/opt/pihole/pihole: line 21: /opt/pihole/COL_TABLE: No such file or directory
/snap/pihole-snap/21/opt/pihole/pihole: line 437: /usr/bin/sudo: Permission denied
/snap/pihole-snap/21/opt/pihole/pihole: line 437: /usr/bin/sudo: Success

Hope you can figure out what's wrong with the path setting under snap confined environment.

Appreciate your effort on building this snap!

**Comment by kz6fittycent** [comment]
It's nowhere near ready for use. I'm not the first to attempt building this snap and it's going to be a long time before I get it done. It's more likely that someone else who's been working on it longer than I will beat me to it - the name was already registered. 

I appreciate your support but I wouldn't hold your breath lol. I just happened to be working on it today and saw your opened issue.
